# Automatically generated by Pynguin.
import pytest
import main as module_0


def test_case_0():
    float_0 = -249.18306
    list_0 = [float_0, float_0]
    float_1 = module_0.mean_absolute_deviation(list_0)
    assert float_1 == pytest.approx(0.0, abs=0.01, rel=0.01)


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    module_0.mean_absolute_deviation(list_0)
