from main import separate_paren_groups

assert separate_paren_groups("") == []
assert separate_paren_groups("(((())))") == ["(((())))"]
assert separate_paren_groups("((()(((())))") == ["((()(((())))"]
assert separate_paren_groups("((()(((())))()") == ["((()(((())))()"]
assert separate_paren_groups("((()()()))") == ["((()()()))"]
assert separate_paren_groups("((())())") == ["((())())"]
assert separate_paren_groups("((()))") == ["((()))"]
assert separate_paren_groups("(()(((())))())") == ["(()(((())))())"]
assert separate_paren_groups("(()((()())))") == ["(()((()())))"]
assert separate_paren_groups("(()(()())())") == ["(()(()())())"]
assert separate_paren_groups("(()(()))(()(()))") == ["(()(()))(()(()))"]
assert separate_paren_groups("(()()()())") == ["(()()()())"]
assert separate_paren_groups("(()())") == ["(()())"]
assert separate_paren_groups("(()())(()())") == ["(()())(()())"]
assert separate_paren_groups("(())") == ["(())"]
assert separate_paren_groups("(())(()())") == ["(())(()())"]
assert separate_paren_groups("(())(())") == ["(())(())"]
assert separate_paren_groups("(())(())(()())") == ["(())(())(()())"]
assert separate_paren_groups("(())(())(())") == ["(())(())(())"]
assert separate_paren_groups("(())(())(())(())") == ["(())(())(())(())"]
assert separate_paren_groups("(())()(())") == ["(())()(())"]
assert separate_paren_groups("(())()(())(())") == ["(())()(())(())"]
assert separate_paren_groups("(())()(())()(())") == ["(())()(())()(())"]
assert separate_paren_groups("((a)(bc)((de)(f)(gh))) (af) (((a)))") == ["((a)(bc)((de)(f)(gh)))", "(af)", "(((a)))"]
assert separate_paren_groups("((a)(bc)((de)(f)(gh))) (af)") == ["((a)(bc)((de)(f)(gh)))", "(af)"]
assert separate_paren_groups("((a)(bc)((de)(f)(gh)))") == ["((a)(bc)((de)(f)(gh)))"]
assert separate_paren_groups("((a))") == ["((a))"]
assert separate_paren_groups("() (())") == ["()","(())"]
assert separate_paren_groups("() () ()") == ["()","()","()"]
assert separate_paren_groups("() ()") == ["()","()"]
assert separate_paren_groups("()") == ["()"]
assert separate_paren_groups("()()") == ["()()"]
assert separate_paren_groups("()()()") == ["()()()"]
assert separate_paren_groups("(a) (d,e,f)") == ["(a)","(d,e,f)"]
assert separate_paren_groups("(a)") == ["(a)"]
assert separate_paren_groups("(a,b,c) (d,e,f) (g,h,i) (j,k,l) (m,n,o) (p,q,r)") == ["(a,b,c)","(d,e,f)","(g,h,i)","(j,k,l)","(m,n,o)","(p,q,r)"]
assert separate_paren_groups("(a,b,c) (d,e,f) (g,h,i) (j,k,l) (m,n,o)") == ["(a,b,c)","(d,e,f)","(g,h,i)","(j,k,l)","(m,n,o)"]
assert separate_paren_groups("(a,b,c) (d,e,f) (g,h,i) (j,k,l)") == ["(a,b,c)","(d,e,f)","(g,h,i)","(j,k,l)"]
assert separate_paren_groups("(a,b,c) (d,e,f) (g,h,i)") == ["(a,b,c)","(d,e,f)","(g,h,i)"]
assert separate_paren_groups("(a,b,c) (d,e,f)") == ["(a,b,c)","(d,e,f)"]
assert separate_paren_groups("(a,b,c)") == ["(a,b,c)"]
assert separate_paren_groups("a(b(c))") == ["a(b(c))"]
assert separate_paren_groups('(()()((()))())') == ['(()()((()))())']
assert separate_paren_groups('(()()(()()((()))))()((()))') == ['(()()(()()((()))))()((()))']
assert separate_paren_groups('(()())') == ['(()())']
assert separate_paren_groups('(())') == ['(())']
assert separate_paren_groups('()') == ['()']
assert separate_paren_groups('(abc)') == ['(abc)']
assert separate_paren_groups('(bar)') == ['(bar)']
assert separate_paren_groups('(foo(bar))') == ['(foo(bar))']